# Generated by Django 2.1.5 on 2019-02-07 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0002_employee_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
    ]
