# Generated by Django 2.1.5 on 2019-02-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0003_remove_employee_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('population', models.IntegerField()),
                ('source_of_income', models.CharField(max_length=40)),
            ],
        ),
    ]
